"""Preprocess MatLab generated CSV file and save the result to a new CSV file.

This script reads a CSV file generated by MatLab, preprocesses it using the
`preprocess_matlab` function from the `sidrobus.preprocessing` module, and saves the
preprocessed data to a new CSV file.
"""

import argparse

import pandas as pd

from sidrobus.preprocessing import preprocess_matlab


def main() -> None:  # noqa: D103
    parser = argparse.ArgumentParser(
        description="Preprocess MatLab generated CSV file."
    )
    parser.add_argument("input_csv", help="Path to the input CSV file")
    parser.add_argument("output_csv", help="Path to the output CSV file")
    args = parser.parse_args()

    input_csv = args.input_csv
    output_csv = args.output_csv

    matlab_data = pd.read_csv(input_csv)
    preprocessed_data = preprocess_matlab(matlab_data)

    preprocessed_data.to_csv(output_csv, index=False)

    print(f"Preprocessed data saved to {output_csv}")


if __name__ == "__main__":
    main()
